server:
  address: ":7966"
  jwt:
    secret: "dev-secret-change"
    expire_hour: 72

database:
  driver: "sqlite"
  path: "easyblog.db"
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "easyblog"
  sslmode: "disable"
  timezone: "Asia/Shanghai"


